# SPDX-License-Identifier: GPL-2.0-or-later
"""
Write SHORTCUTS.md: every shortcut the Maelstrom3D keymap changes, before and after.

    blender -b --factory-startup --python tools/m3d/shortcuts_doc.py -- SHORTCUTS.md
"""

import os
import sys

import bpy

OUT = sys.argv[sys.argv.index("--") + 1]
PRESETS = os.path.join(bpy.utils.resource_path('LOCAL'), "scripts", "presets", "keyconfig")
ic = bpy.utils.execfile(os.path.join(PRESETS, "keymap_data", "industry_compatible_data.py"))
maya = bpy.utils.execfile(os.path.join(PRESETS, "Maelstrom3D.py"))

MOD_NAMES = (("ctrl", "Ctrl"), ("shift", "Shift"), ("alt", "Alt"), ("oskey", "Cmd"))
KEY_NAMES = {
    'LEFTMOUSE': "LMB", 'RIGHTMOUSE': "RMB", 'MIDDLEMOUSE': "MMB", 'COMMA': ",", 'PERIOD': ".",
    'ONE': "1", 'TWO': "2", 'THREE': "3", 'FOUR': "4", 'FIVE': "5", 'SIX': "6", 'SEVEN': "7",
    'EQUAL': "=", 'MINUS': "-", 'DEL': "Delete", 'BACK_SPACE': "Backspace", 'UP_ARROW': "Up",
    'DOWN_ARROW': "Down", 'PAGE_UP': "Page Up", 'PAGE_DOWN': "Page Down", 'SPACE': "Space",
    'INSERT': "Insert",
}
VALUE_NAMES = {'PRESS': "", 'RELEASE': " (release)", 'CLICK': " click", 'CLICK_DRAG': " drag",
               'DOUBLE_CLICK': " double-click"}


def key_text(args):
    mods = [name for attr, name in MOD_NAMES if args.get(attr)]
    key = KEY_NAMES.get(args["type"], args["type"].replace("_", " ").title())
    return "+".join(mods + [key]) + VALUE_NAMES.get(args["value"], " " + args["value"].lower())


def action_text(idname, data):
    if idname == "REMOVE":
        return "*(removed)*"
    props = dict(data.get("properties", ())) if data else {}
    if idname in {"wm.call_menu_pie", "wm.call_menu"}:
        menu = getattr(bpy.types, props["name"], None)
        return "Menu: " + ((menu.bl_label if menu else "") or props["name"])
    if idname == "brush.asset_activate":
        return "Brush: " + props["relative_asset_identifier"].partition("/Brush/")[2]
    if idname == "wm.tool_set_by_id":
        return "Tool: " + props["name"].split(".")[-1].replace("_", " ").title()
    if idname.startswith("wm.context_"):
        path = " ".join(props.get("data_path", "").split(".")[-2:]).replace("_", " ")
        if idname.startswith("wm.context_scale"):
            return f"Scale {path} x{props['value']}"
        return f"Set {path} = {props['value']}" if "value" in props else "Toggle " + path
    mod, name = idname.split(".")
    try:
        label = getattr(getattr(bpy.ops, mod), name).get_rna_type().name
    except (KeyError, AttributeError):
        label = idname
    extra = ", ".join(f"{k}={v!r}" for k, v in props.items())
    return f"{label} ({extra})" if extra else label


def main():
    before = {name: content["items"] for name, _args, content in ic.generate_keymaps(ic.Params())}
    lines = [
        "# Maelstrom3D shortcut changes",
        "",
        "Generated by `tools/m3d/shortcuts_doc.py`. The Maelstrom3D keymap starts from Blender's",
        "**Industry Compatible** keymap (which already has Alt+mouse navigation, QWERT tools,",
        "F/A framing and Ctrl+D duplicate) and changes the shortcuts below.",
        "",
        "## Selection modifiers (all editors)",
        "",
        "| Input | Industry Compatible | Maelstrom3D |",
        "|---|---|---|",
        "| Ctrl+click | Select (center / object) | Deselect |",
        "| Ctrl+Shift+click | Extend + toggle | Add to selection |",
        "| Shift+drag (box/lasso) | Add | Toggle (UV editor: add) |",
        "| Ctrl+drag | Subtract | Deselect (subtract) |",
        "| Ctrl+Shift+drag | Intersect | Add |",
        "",
    ]
    for km_name, items in maya.OVERRIDES.items():
        old_items = before.get(km_name, [])
        lines += [f"## {km_name}", "", "| Key | Before (Industry Compatible) | Now (Maelstrom3D) |", "|---|---|---|"]
        seen = set()
        for idname, args, data in items:
            key = maya._key(args)
            old = [action_text(i, d) for i, a, d in old_items if maya._key(a) == key]
            now = action_text(idname, data)
            row = (key_text(args), "<br>".join(old) or "—", now)
            if row not in seen:
                seen.add(row)
                lines.append("| %s | %s | %s |" % row)
        lines.append("")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("wrote", OUT)


main()
